[package]
name = "waypie"
version = "2.0.0"
edition = "2024"
license = "MIT"
description = "A lightweight Kando-like radial menu for Wayland"
repository = "https://github.com/rywby-dot/waypie"
include = [
    "src/**",
    "config/config",
    "config/style.css",
    "config/style_foot.css",
    "Cargo.toml",
    "Cargo.lock",
    "LICENSE",
    "README.md",
]

[dependencies]
anyhow = "1"
cosmic-text = "0.17"
dirs = "6"
image = { version = "0.25", default-features = false, features = ["gif", "jpeg", "png", "webp"] }
resvg = "0.45"
serde = { version = "1", features = ["derive"] }
smithay-client-toolkit = "0.19.2"
tiny-skia = "0.11.4"
toml = "0.9"
wayland-client = "0.31.11"
wayland-protocols-wlr = "0.3.12"

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
panic = "abort"
strip = true
